// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZM6QDQPEJEsDNM9RAWwKqsK5uOXfues',
    appId: '1:568348724078:web:582fe5530752ed036b0f7f',
    messagingSenderId: '568348724078',
    projectId: 'mystroke-c4378',
    authDomain: 'mystroke-c4378.firebaseapp.com',
    storageBucket: 'mystroke-c4378.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzWpif8-t7pNcWWp2stW7J_wxz44BaHTw',
    appId: '1:568348724078:android:18c907a6563808b16b0f7f',
    messagingSenderId: '568348724078',
    projectId: 'mystroke-c4378',
    storageBucket: 'mystroke-c4378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVdDwwYxt0rw2jmK2IA2aMikLMyPEvdxw',
    appId: '1:568348724078:ios:e63e13067c73f7b26b0f7f',
    messagingSenderId: '568348724078',
    projectId: 'mystroke-c4378',
    storageBucket: 'mystroke-c4378.appspot.com',
    iosBundleId: 'com.example.mystrokeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVdDwwYxt0rw2jmK2IA2aMikLMyPEvdxw',
    appId: '1:568348724078:ios:e63e13067c73f7b26b0f7f',
    messagingSenderId: '568348724078',
    projectId: 'mystroke-c4378',
    storageBucket: 'mystroke-c4378.appspot.com',
    iosBundleId: 'com.example.mystrokeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtZM6QDQPEJEsDNM9RAWwKqsK5uOXfues',
    appId: '1:568348724078:web:6dc8aa049aa6fa4b6b0f7f',
    messagingSenderId: '568348724078',
    projectId: 'mystroke-c4378',
    authDomain: 'mystroke-c4378.firebaseapp.com',
    storageBucket: 'mystroke-c4378.appspot.com',
  );
}
